#include "stdafx.h"
#include "scriptvariable.h"
#include "scripttimermanager.h"

DEFINE_SCRIPT_VAR(YEAR) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wYear);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(MONTH) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wMonth);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(DAY) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wDay);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(HOUR) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wHour);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(MINUTE) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wMinute);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(SECOND) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	result.SetValue((UINT)st.wSecond);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(DATETIMETOWOLTIME) {
	DWORD dwNow = (DWORD)time(nullptr);
	result.SetValue(dwNow);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(SERVERDATETIME) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	char* p = CScriptVariableManager::GetInstance()->GetStringCache();
	sprintf(p, "%04u-%02u-%02u %02u:%02u:%02u",
		st.wYear, st.wMonth, st.wDay,
		st.wHour, st.wMinute, st.wSecond);
	result.SetValue(p);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(SERVERDATE) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	char* p = CScriptVariableManager::GetInstance()->GetStringCache();
	sprintf(p, "%04u-%02u-%02u",
		st.wYear, st.wMonth, st.wDay);
	result.SetValue(p);
}END_SCRIPT_VAR

DEFINE_SCRIPT_VAR(SERVERTIME) {
	SYSTEMTIME	st;
	GetLocalTime(&st);
	char* p = CScriptVariableManager::GetInstance()->GetStringCache();
	sprintf(p, "%02u:%02u:%02u",
		st.wHour, st.wMinute, st.wSecond);
	result.SetValue(p);
}END_SCRIPT_VAR


#define	TIMERVAR_DEFINE( index ) DEFINE_SCRIPT_VAR( TIMER##index##TIME ){ \
	result.SetValue( (UINT)CScriptTimerManager::GetInstance()->GetTimerTime( (index) ) );\
}END_SCRIPT_VAR
//TIMERVAR_DEFINE( 0 );
TIMERVAR_DEFINE(1);
TIMERVAR_DEFINE(2);
TIMERVAR_DEFINE(3);
TIMERVAR_DEFINE(4);
TIMERVAR_DEFINE(5);
TIMERVAR_DEFINE(6);
TIMERVAR_DEFINE(7);
TIMERVAR_DEFINE(8);
TIMERVAR_DEFINE(9);
TIMERVAR_DEFINE(10);
TIMERVAR_DEFINE(11);
TIMERVAR_DEFINE(12);
TIMERVAR_DEFINE(13);
TIMERVAR_DEFINE(14);
TIMERVAR_DEFINE(15);
TIMERVAR_DEFINE(16);
TIMERVAR_DEFINE(17);
TIMERVAR_DEFINE(18);
TIMERVAR_DEFINE(19);
TIMERVAR_DEFINE(20);
TIMERVAR_DEFINE(21);
TIMERVAR_DEFINE(22);
TIMERVAR_DEFINE(23);
TIMERVAR_DEFINE(24);
TIMERVAR_DEFINE(25);
TIMERVAR_DEFINE(26);
TIMERVAR_DEFINE(27);
TIMERVAR_DEFINE(28);
TIMERVAR_DEFINE(29);
TIMERVAR_DEFINE(30);
TIMERVAR_DEFINE(31);
TIMERVAR_DEFINE(32);
TIMERVAR_DEFINE(33);
TIMERVAR_DEFINE(34);
TIMERVAR_DEFINE(35);
TIMERVAR_DEFINE(36);
TIMERVAR_DEFINE(37);
TIMERVAR_DEFINE(38);
TIMERVAR_DEFINE(39);
TIMERVAR_DEFINE(40);
TIMERVAR_DEFINE(41);
TIMERVAR_DEFINE(42);
TIMERVAR_DEFINE(43);
TIMERVAR_DEFINE(44);
TIMERVAR_DEFINE(45);
TIMERVAR_DEFINE(46);
TIMERVAR_DEFINE(47);
TIMERVAR_DEFINE(48);
TIMERVAR_DEFINE(49);
TIMERVAR_DEFINE(50);
TIMERVAR_DEFINE(51);
TIMERVAR_DEFINE(52);
TIMERVAR_DEFINE(53);
TIMERVAR_DEFINE(54);
TIMERVAR_DEFINE(55);
TIMERVAR_DEFINE(56);
TIMERVAR_DEFINE(57);
TIMERVAR_DEFINE(58);
TIMERVAR_DEFINE(59);
TIMERVAR_DEFINE(60);
TIMERVAR_DEFINE(61);
TIMERVAR_DEFINE(62);
TIMERVAR_DEFINE(63);
TIMERVAR_DEFINE(64);
TIMERVAR_DEFINE(65);
TIMERVAR_DEFINE(66);
TIMERVAR_DEFINE(67);
TIMERVAR_DEFINE(68);
TIMERVAR_DEFINE(69);
TIMERVAR_DEFINE(70);
TIMERVAR_DEFINE(71);
TIMERVAR_DEFINE(72);
TIMERVAR_DEFINE(73);
TIMERVAR_DEFINE(74);
TIMERVAR_DEFINE(75);
TIMERVAR_DEFINE(76);
TIMERVAR_DEFINE(77);
TIMERVAR_DEFINE(78);
TIMERVAR_DEFINE(79);
TIMERVAR_DEFINE(80);
TIMERVAR_DEFINE(81);
TIMERVAR_DEFINE(82);
TIMERVAR_DEFINE(83);
TIMERVAR_DEFINE(84);
TIMERVAR_DEFINE(85);
TIMERVAR_DEFINE(86);
TIMERVAR_DEFINE(87);
TIMERVAR_DEFINE(88);
TIMERVAR_DEFINE(89);
TIMERVAR_DEFINE(90);
TIMERVAR_DEFINE(91);
TIMERVAR_DEFINE(92);
TIMERVAR_DEFINE(93);
TIMERVAR_DEFINE(94);
TIMERVAR_DEFINE(95);
TIMERVAR_DEFINE(96);
TIMERVAR_DEFINE(97);
TIMERVAR_DEFINE(98);
TIMERVAR_DEFINE(99);
TIMERVAR_DEFINE(100);
TIMERVAR_DEFINE(101);
TIMERVAR_DEFINE(102);
TIMERVAR_DEFINE(103);
TIMERVAR_DEFINE(104);
TIMERVAR_DEFINE(105);
TIMERVAR_DEFINE(106);
TIMERVAR_DEFINE(107);
TIMERVAR_DEFINE(108);
TIMERVAR_DEFINE(109);
TIMERVAR_DEFINE(110);
TIMERVAR_DEFINE(111);
TIMERVAR_DEFINE(112);
TIMERVAR_DEFINE(113);
TIMERVAR_DEFINE(114);
TIMERVAR_DEFINE(115);
TIMERVAR_DEFINE(116);
TIMERVAR_DEFINE(117);
TIMERVAR_DEFINE(118);
TIMERVAR_DEFINE(119);
TIMERVAR_DEFINE(120);
TIMERVAR_DEFINE(121);
TIMERVAR_DEFINE(122);
TIMERVAR_DEFINE(123);
TIMERVAR_DEFINE(124);
TIMERVAR_DEFINE(125);
TIMERVAR_DEFINE(126);
TIMERVAR_DEFINE(127);
TIMERVAR_DEFINE(128);
TIMERVAR_DEFINE(129);
TIMERVAR_DEFINE(130);
TIMERVAR_DEFINE(131);
TIMERVAR_DEFINE(132);
TIMERVAR_DEFINE(133);
TIMERVAR_DEFINE(134);
TIMERVAR_DEFINE(135);
TIMERVAR_DEFINE(136);
TIMERVAR_DEFINE(137);
TIMERVAR_DEFINE(138);
TIMERVAR_DEFINE(139);
TIMERVAR_DEFINE(140);
TIMERVAR_DEFINE(141);
TIMERVAR_DEFINE(142);
TIMERVAR_DEFINE(143);
TIMERVAR_DEFINE(144);
TIMERVAR_DEFINE(145);
TIMERVAR_DEFINE(146);
TIMERVAR_DEFINE(147);
TIMERVAR_DEFINE(148);
TIMERVAR_DEFINE(149);
TIMERVAR_DEFINE(150);
TIMERVAR_DEFINE(151);
TIMERVAR_DEFINE(152);
TIMERVAR_DEFINE(153);
TIMERVAR_DEFINE(154);
TIMERVAR_DEFINE(155);
TIMERVAR_DEFINE(156);
TIMERVAR_DEFINE(157);
TIMERVAR_DEFINE(158);
TIMERVAR_DEFINE(159);
TIMERVAR_DEFINE(160);
TIMERVAR_DEFINE(161);
TIMERVAR_DEFINE(162);
TIMERVAR_DEFINE(163);
TIMERVAR_DEFINE(164);
TIMERVAR_DEFINE(165);
TIMERVAR_DEFINE(166);
TIMERVAR_DEFINE(167);
TIMERVAR_DEFINE(168);
TIMERVAR_DEFINE(169);
TIMERVAR_DEFINE(170);
TIMERVAR_DEFINE(171);
TIMERVAR_DEFINE(172);
TIMERVAR_DEFINE(173);
TIMERVAR_DEFINE(174);
TIMERVAR_DEFINE(175);
TIMERVAR_DEFINE(176);
TIMERVAR_DEFINE(177);
TIMERVAR_DEFINE(178);
TIMERVAR_DEFINE(179);
TIMERVAR_DEFINE(180);
TIMERVAR_DEFINE(181);
TIMERVAR_DEFINE(182);
TIMERVAR_DEFINE(183);
TIMERVAR_DEFINE(184);
TIMERVAR_DEFINE(185);
TIMERVAR_DEFINE(186);
TIMERVAR_DEFINE(187);
TIMERVAR_DEFINE(188);
TIMERVAR_DEFINE(189);
TIMERVAR_DEFINE(190);
TIMERVAR_DEFINE(191);
TIMERVAR_DEFINE(192);
TIMERVAR_DEFINE(193);
TIMERVAR_DEFINE(194);
TIMERVAR_DEFINE(195);
TIMERVAR_DEFINE(196);
TIMERVAR_DEFINE(197);
TIMERVAR_DEFINE(198);
TIMERVAR_DEFINE(199);
TIMERVAR_DEFINE(200);
TIMERVAR_DEFINE(201);
TIMERVAR_DEFINE(202);
TIMERVAR_DEFINE(203);
TIMERVAR_DEFINE(204);
TIMERVAR_DEFINE(205);
TIMERVAR_DEFINE(206);
TIMERVAR_DEFINE(207);
TIMERVAR_DEFINE(208);
TIMERVAR_DEFINE(209);
TIMERVAR_DEFINE(210);
TIMERVAR_DEFINE(211);
TIMERVAR_DEFINE(212);
TIMERVAR_DEFINE(213);
TIMERVAR_DEFINE(214);
TIMERVAR_DEFINE(215);
TIMERVAR_DEFINE(216);
TIMERVAR_DEFINE(217);
TIMERVAR_DEFINE(218);
TIMERVAR_DEFINE(219);
TIMERVAR_DEFINE(220);
TIMERVAR_DEFINE(221);
TIMERVAR_DEFINE(222);
TIMERVAR_DEFINE(223);
TIMERVAR_DEFINE(224);
TIMERVAR_DEFINE(225);
TIMERVAR_DEFINE(226);
TIMERVAR_DEFINE(227);
TIMERVAR_DEFINE(228);
TIMERVAR_DEFINE(229);
TIMERVAR_DEFINE(230);
TIMERVAR_DEFINE(231);
TIMERVAR_DEFINE(232);
TIMERVAR_DEFINE(233);
TIMERVAR_DEFINE(234);
TIMERVAR_DEFINE(235);
TIMERVAR_DEFINE(236);
TIMERVAR_DEFINE(237);
TIMERVAR_DEFINE(238);
TIMERVAR_DEFINE(239);
TIMERVAR_DEFINE(240);
TIMERVAR_DEFINE(241);
TIMERVAR_DEFINE(242);
TIMERVAR_DEFINE(243);
TIMERVAR_DEFINE(244);
TIMERVAR_DEFINE(245);
TIMERVAR_DEFINE(246);
TIMERVAR_DEFINE(247);
TIMERVAR_DEFINE(248);
TIMERVAR_DEFINE(249);
TIMERVAR_DEFINE(250);
TIMERVAR_DEFINE(251);
TIMERVAR_DEFINE(252);
TIMERVAR_DEFINE(253);
TIMERVAR_DEFINE(254);
TIMERVAR_DEFINE(255);
TIMERVAR_DEFINE(256);