/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Zhou Quan                             **
********************************************************************/

/*       Version Number: 1          */

#ifndef CLIGGPROTO_H_INCLUDE_VERSION_1
#define CLIGGPROTO_H_INCLUDE_VERSION_1

#include "netdata.h"
#include "commdefs.h"

/*Defines Begin*/
#define VERIFY_PIC_LEN           9216
#define VERIFY_STR_LEN           16
#define DYNCODE_BUF_LEN          9216
#define GROUP_MAX_NUM            16
#define CLIGGPROTO_MSGID_RANGE 147
#define CLIGGPROTO_MSGID_OFFSET 1
/*Defines End*/


/*Define Structs and Unions        Begin*/
typedef struct tagSGroupName{
	unsigned short   wNameLen;
	unsigned char    abyName[GROUPNAME_LEN];
}SGroupName;

typedef struct tagPKG_LG_CLI_GroupList_NTF{
	unsigned char    byCount;
	SGroupName       astNameList[GROUP_MAX_NUM];
}PKG_LG_CLI_GroupList_NTF;

typedef struct tagPKG_CLI_LG_SelGroup_REQ{
	char             szName[GROUPNAME_LEN];
}PKG_CLI_LG_SelGroup_REQ;

typedef union tagUSelGroupAck{
	SIPAddr          stSucc;
	SErrCode         stFail;
}USelGroupAck;

typedef struct tagPKG_LG_CLI_SelGroup_ACK{
	unsigned char    byResult;
	USelGroupAck     stReply;
}PKG_LG_CLI_SelGroup_ACK;

typedef struct tagPKG_LG_CLI_SS_INFO{
	unsigned char    byResult;
	USelGroupAck     stReply;
}PKG_LG_CLI_SS_INFO;

typedef struct tagPKG_CLI_GG_DynCode_REQ{
	unsigned char    byClientType;
}PKG_CLI_GG_DynCode_REQ;

typedef struct tagPKG_GG_CLI_DynCode_NTF{
	unsigned int     dwDataLen;
	unsigned char    abyDataBuf[DYNCODE_BUF_LEN];
}PKG_GG_CLI_DynCode_NTF;

typedef struct tagPKG_CLI_GG_PTLogin_REQ{
	char             szPTID[PTID_LEN];
	char             szPasswd[PASSWORD_LEN];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_PTLogin_REQ;

typedef struct tagPKG_CLI_GG_SDOALogin_REQ{
	char             szDigitID[PTID_LEN];
	unsigned int     dwClientVersion;
	unsigned short   wTokenLen;
	unsigned char    abyToken[TOKEN_LEN];
}PKG_CLI_GG_SDOALogin_REQ;

typedef struct tagPKG_CLI_GG_MailLogin_REQ{
	char             szMailID[MAIL_LEN];
	char             szPasswd[PASSWORD_LEN];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_MailLogin_REQ;

typedef struct tagPKG_CLI_GG_SpeTokenLogin_REQ{
	unsigned int     dwClientVersion;
	unsigned short   wTokenLen;
	unsigned char    abyToken[TOKEN_LEN];
}PKG_CLI_GG_SpeTokenLogin_REQ;

typedef struct tagPKG_CLI_GG_SpePwdLogin_REQ{
	char             szAccountID[ACCOUNT_LEN];
	char             szPasswd[SPEPWD_LEN];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_SpePwdLogin_REQ;

typedef struct tagPKG_CLI_GG_APLogin_REQ{
	char             szAuthAct[64];
	char             szAuthStr[AP_AUTH_STR_LEN];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_APLogin_REQ;

typedef struct tagPKG_CLI_GG_EXPLogin_REQ{
	unsigned int     dwClientVersion;
}PKG_CLI_GG_EXPLogin_REQ;

typedef struct tagPKG_CLI_GG_SGILogin_REQ{
	char             szPlatform[64];
	char             szAuthCode[512];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_SGILogin_REQ;

typedef union tagLoginReqInfo{
	PKG_CLI_GG_PTLogin_REQ stPTLoginReq;
	PKG_CLI_GG_SDOALogin_REQ stSDOALoginReq;
	PKG_CLI_GG_MailLogin_REQ stMailLoginReq;
	PKG_CLI_GG_SpeTokenLogin_REQ stSpeTkLoginReq;
	PKG_CLI_GG_SpePwdLogin_REQ stSpePwdLoginReq;
	PKG_CLI_GG_APLogin_REQ stAPLoginReq;
	PKG_CLI_GG_EXPLogin_REQ stEXPLoginReq;
	PKG_CLI_GG_SGILogin_REQ stSGILoginReq;
}LoginReqInfo;

typedef struct tagPKG_CLI_GG_Login_REQ{
	unsigned char    byType;
	LoginReqInfo     stInfo;
}PKG_CLI_GG_Login_REQ;

typedef struct tagPKG_GG_CLI_Challenge_REQ{
	unsigned char    byType;
	char             szChallenge[CHALLENGE_MAX_LEN];
}PKG_GG_CLI_Challenge_REQ;

typedef struct tagPKG_CLI_GG_Challenge_ACK{
	unsigned char    byType;
	char             szDPWD[DPWD_LEN];
}PKG_CLI_GG_Challenge_ACK;

typedef struct tagPKG_GG_CLI_Login_SUC{
	unsigned long long qwDigitID;
	LoginData        stLoginData;
	SRoleList        stRoleList;
}PKG_GG_CLI_Login_SUC;

typedef struct tagPKG_GG_CLI_APLogin_RES{
	int              nResult;
	char             szAuthAct[64];
	char             szAuthResStr[AP_AUTH_RES_STR_LEN];
	unsigned long long qwDigitID;
	LoginData        stLoginData;
	SRoleList        stRoleList;
	char             szchannel[64];
	char             szaccount[128];
}PKG_GG_CLI_APLogin_RES;

typedef struct tagPKG_GG_CLI_EXPLogin_RES{
	int              nResult;
	unsigned long long qwDigitID;
	LoginData        stLoginData;
	SRoleList        stRoleList;
}PKG_GG_CLI_EXPLogin_RES;

typedef struct tagPKG_GG_CLI_SGILogin_RES{
	int              nResult;
	unsigned long long qwDigitID;
	LoginData        stLoginData;
	SRoleList        stRoleList;
}PKG_GG_CLI_SGILogin_RES;

typedef union tagPKG_GG_CLI_Login_UN{
	PKG_GG_CLI_Login_SUC stSucc;
	SErrCode         stFail;
	PKG_GG_CLI_APLogin_RES stAPRes;
	PKG_GG_CLI_EXPLogin_RES stEXPRes;
	PKG_GG_CLI_SGILogin_RES stSGIRes;
}PKG_GG_CLI_Login_UN;

typedef struct tagPKG_GG_CLI_Login_ACK{
	char             szPTID[PTID_LEN];
	unsigned char    byResult;
	PKG_GG_CLI_Login_UN stReply;
}PKG_GG_CLI_Login_ACK;

typedef struct tagPKG_GG_CLI_Verify_REQ{
	unsigned short   wPicLen;
	unsigned char    abyPicture[VERIFY_PIC_LEN];
}PKG_GG_CLI_Verify_REQ;

typedef struct tagPKG_CLI_GG_Verify_ACK{
	char             szAnswer[VERIFY_STR_LEN];
}PKG_CLI_GG_Verify_ACK;

typedef struct tagPKG_CLI_GG_SelectRole_REQ{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
}PKG_CLI_GG_SelectRole_REQ;

typedef struct tagSelRoleRet{
	unsigned int     dwNPC;
	unsigned char    byServerNo;
	unsigned short   wAreaNo;
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[ONLINEMSG_LEN];
}SelRoleRet;

typedef union tagPKG_GG_CLI_SelectRole_UN{
	SelRoleRet       stSucc;
	SErrCode         stFail;
}PKG_GG_CLI_SelectRole_UN;

typedef struct tagPKG_GG_CLI_SelectRole_ACK{
	unsigned char    byResult;
	PKG_GG_CLI_SelectRole_UN stReply;
}PKG_GG_CLI_SelectRole_ACK;

typedef struct tagPKG_CLI_GG_CreateRole_REQ{
	SCreateRoleInfo  stInfo;
}PKG_CLI_GG_CreateRole_REQ;

typedef struct tagPKG_GG_CLI_CreateRole_ACK{
	unsigned char    byResult;
	URoleOpAck       stReply;
}PKG_GG_CLI_CreateRole_ACK;

typedef struct tagPKG_CLI_GG_DelRole_REQ{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
}PKG_CLI_GG_DelRole_REQ;

typedef struct tagPKG_GG_CLI_DelRole_ACK{
	unsigned char    byResult;
	SErrCode         stReason;
}PKG_GG_CLI_DelRole_ACK;

typedef struct tagPKG_CLI_GG_UnDelRole_REQ{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
}PKG_CLI_GG_UnDelRole_REQ;

typedef struct tagPKG_GG_CLI_UnDelRole_ACK{
	unsigned char    byResult;
	SErrCode         stReason;
}PKG_GG_CLI_UnDelRole_ACK;

typedef struct tagPKG_CLI_GG_Logout_NTF{
	char             szPTID[PTID_LEN];
}PKG_CLI_GG_Logout_NTF;

typedef struct tagPKG_CLI_GG_ReselRole_REQ{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
}PKG_CLI_GG_ReselRole_REQ;

typedef union tagPKG_GG_CLI_ReselRole_UN{
	SRoleList        stSucc;
	SErrCode         stFail;
}PKG_GG_CLI_ReselRole_UN;

typedef struct tagPKG_GG_CLI_ReselRole_ACK{
	unsigned char    byResult;
	PKG_GG_CLI_ReselRole_UN stReply;
}PKG_GG_CLI_ReselRole_ACK;

typedef struct tagPKG_GG_CLI_KickOff_NTF{
	unsigned short   wReason;
}PKG_GG_CLI_KickOff_NTF;

typedef struct tagPKG_CLI_GG_VerifyStoreEkey_ACK{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
	char             szDPWD[DPWD_LEN];
}PKG_CLI_GG_VerifyStoreEkey_ACK;

typedef struct tagPKG_CLI_GG_FCMFillInfo_REQ{
	char             szPTID[PTID_LEN];
	char             szName[NAME_MAX_LEN];
	char             szIDCard[IDCard_MAX_LEN];
	unsigned char    byFCMFlag;
}PKG_CLI_GG_FCMFillInfo_REQ;

typedef struct tagPKG_GG_CLI_ReservePwd_REQ{
}PKG_GG_CLI_ReservePwd_REQ;

typedef struct tagPKG_CLI_GG_ReservePwd_ACK{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
	char             szDPWD[DPWD_LEN];
}PKG_CLI_GG_ReservePwd_ACK;

typedef struct tagPKG_CLI_GG_Extend_MSG{
	unsigned int     dwExtendID;
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[LOGINMSG_LEN];
}PKG_CLI_GG_Extend_MSG;

typedef struct tagPKG_GG_CLI_Extend_MSG{
	unsigned int     dwExtendID;
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[LOGINMSG_LEN];
}PKG_GG_CLI_Extend_MSG;

typedef struct tagPKG_GG_CLI_GroupInfo_NTF{
	unsigned short   wAreaId;
	unsigned short   wGroupId;
}PKG_GG_CLI_GroupInfo_NTF;

typedef struct tagPKG_CLI_GG_OfflineTrustee_NTF{
	unsigned char    byTrusteeMode;
}PKG_CLI_GG_OfflineTrustee_NTF;

typedef struct tagPKG_GG_CLI_NeedAuthen_REQ{
	char             szAuthenURL[URL_MAX_LEN];
}PKG_GG_CLI_NeedAuthen_REQ;

typedef struct tagPKG_CLI_GG_NeedAuthen_ACK{
	unsigned char    byReserve;
}PKG_CLI_GG_NeedAuthen_ACK;

typedef struct tagPKG_GG_CLI_QQInfo_NTF{
	unsigned short   wAreaId;
	unsigned short   wGroupId;
	unsigned char    byOA;
	unsigned char    byQQ2;
	unsigned char    byTrustee;
}PKG_GG_CLI_QQInfo_NTF;

typedef struct tagPKG_GG_CLI_InGameVerify_REQ{
	unsigned short   wPopupTime;
	unsigned short   wTotalTime;
	unsigned short   wPicLen;
	unsigned char    abyPicture[VERIFY_PIC_LEN];
}PKG_GG_CLI_InGameVerify_REQ;

typedef struct tagPKG_CLI_GG_InGameVerify_ACK{
	char             szAnswer[VERIFY_STR_LEN];
}PKG_CLI_GG_InGameVerify_ACK;

typedef struct tagPKG_CLI_GG_FreshVerify_Req{
	unsigned char    byReserve;
}PKG_CLI_GG_FreshVerify_Req;

typedef struct tagPKG_GG_CLI_LoginVerify_REQ{
	char             szVerifyURL[URL_MAX_LEN];
}PKG_GG_CLI_LoginVerify_REQ;

typedef struct tagPKG_CLI_GG_LoginVerify_ACK{
	char             szAnswer[VERIFY_STR_LEN];
}PKG_CLI_GG_LoginVerify_ACK;

typedef struct tagPKG_CLI_GG_MERGE_PT_REQ{
	char             szAccount[256];
	char             szPasswd[PASSWORD_LEN];
	unsigned int     dwClientVersion;
}PKG_CLI_GG_MERGE_PT_REQ;

typedef struct tagPKG_CLI_GG_MERGE_PT_ACK{
	int              nResult;
}PKG_CLI_GG_MERGE_PT_ACK;

/*Define Structs and Unions        End*/

//´«ÊÀ·â°ü
#define	SM_QUERYCHR				520			//	Ä³¸¯¸®½ºÆ®
#define	SM_STARTPLAY			525			//	°³ÀÓ½ÃÀÛ
#define	SM_STARTFAIL			526			//	°³ÀÓ½ÃÀÛ ½ÇÆÐ
#define	SM_SELECTSERVER_OK		530			//	¼­¹ö¼±ÅÃ (Á¢¼Ó ¹ö¼­ IPµîÀÇ Á¤º¸°¡ µé¾î°¨)

#define CM_NEWCHR				101			//´´½¨½ÇÉ«
#define CM_SELCHR				103			//Ñ¡Ôñ½ÇÉ«
#define CM_IDPASSWORD			2001			// µÇÂ¼ÇëÇó
#define	SM_PASSWD_SUCC			511			//µÇÂ½³É¹¦
#define	SM_PASSWD_FAIL			503			// µÇÂ½Ê§°Ü,ÕËºÅÃÜÂë´íÎó 

enum EN_CliGgProto_MessageID
{
	LG_CLI_GroupList_NTF            = 1           ,
	CLI_LG_SelGroup_REQ           /*= 2         */, 
	LG_CLI_SelGroup_ACK           /*= 3         */, 
	LG_CLI_SS_INFO                /*= 4         */, 
	CLI_GG_DelRole_REQ              = 102         ,  //lzhez É¾³ý½ÇÉ«ÓÉ120¸ÄÎª102Óë·þÎñ¶Ë¶ÔÓ¦
	CLI_GG_Login_REQ                = 110         ,
	GG_CLI_Login_ACK              /*= 111       */, 
	GG_CLI_Challenge_REQ          /*= 112       */, 
	CLI_GG_Challenge_ACK          /*= 113       */, 
	GG_CLI_Verify_REQ             /*= 114       */, 
	CLI_GG_Verify_ACK             /*= 115       */, 
	CLI_GG_SelectRole_REQ         /*= 116       */, 
	GG_CLI_SelectRole_ACK         /*= 117       */, 
	CLI_GG_CreateRole_REQ         /*= 118       */, 
	GG_CLI_CreateRole_ACK         /*= 119       */, 
	//CLI_GG_DelRole_REQ            /*= 120       */,   //lzhez ×¢ÊÍ
	//GG_CLI_DelRole_ACK              = 121         ,   //lzhez ×¢ÊÍ
	CLI_GG_ReselRole_REQ            = 122         , 
	GG_CLI_ReselRole_ACK          /*= 123       */, 
	CLI_GG_UnDelRole_REQ          /*= 124       */, 
	//GG_CLI_UnDelRole_ACK          /*= 125       */,   //lzhez ×¢ÊÍ
	GG_CLI_KickOff_NTF               = 126         , 
	CLI_GG_Logout_NTF             /*= 127       */, 
	CLI_GG_DynCode_REQ            /*= 128       */, 
	GG_CLI_DynCode_NTF            /*= 129       */, 
	CLI_GG_VerifyStoreEkey_ACK    /*= 130       */, 
	CLI_GG_FCMFillInfo_REQ        /*= 131       */, 
	GG_CLI_ReservePwd_REQ         /*= 132       */, 
	CLI_GG_ReservePwd_ACK         /*= 133       */, 
	CLI_GG_Extend_MSG             /*= 134       */, 
	GG_CLI_Extend_MSG             /*= 135       */, 
	GG_CLI_GroupInfo_NTF          /*= 136       */, 
	CLI_GG_OfflineTrustee_NTF     /*= 137       */, 
	GG_CLI_NeedAuthen_REQ         /*= 138       */, 
	CLI_GG_NeedAuthen_ACK         /*= 139       */, 
	GG_CLI_QQInfo_NTF             /*= 140       */, 
	GG_CLI_InGameVerify_REQ       /*= 141       */, 
	CLI_GG_InGameVerify_ACK       /*= 142       */, 
	CLI_GG_FreshVerify_Req        /*= 143       */, 
	GG_CLI_LoginVerify_REQ        /*= 144       */, 
	CLI_GG_LoginVerify_ACK        /*= 145       */, 
	CLI_GG_MERGE_PT_REQ           /*= 146       */, 
	CLI_GG_MERGE_PT_ACK           /*= 147       */, 
	GG_CLI_DelRole_ACK              = 523         ,  //lzhez É¾³ý½ÇÉ«³É¹¦ºóÏìÓ¦
	GG_CLI_UnDelRole_ACK          /*= 524       */,  //lzhez É¾³ý½ÇÉ«Ê§°ÜºóÏìÓ¦
};

/*Encode and Decode Function Declare Begin*/
int EncodeSGroupName(void *pHost, CNetData* poNetData);
int DecodeSGroupName(void *pHost, CNetData* poNetData);
int EncodePKG_LG_CLI_GroupList_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_LG_CLI_GroupList_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_LG_SelGroup_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_LG_SelGroup_REQ(void *pHost, CNetData* poNetData);
int EncodeUnUSelGroupAck(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnUSelGroupAck(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_LG_CLI_SelGroup_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_LG_CLI_SelGroup_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_LG_CLI_SS_INFO(void *pHost, CNetData* poNetData);
int DecodePKG_LG_CLI_SS_INFO(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_DynCode_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_DynCode_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_DynCode_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_DynCode_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_PTLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_PTLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_SDOALogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_SDOALogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_MailLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_MailLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_SpeTokenLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_SpeTokenLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_SpePwdLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_SpePwdLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_APLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_APLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_EXPLogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_EXPLogin_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_SGILogin_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_SGILogin_REQ(void *pHost, CNetData* poNetData);
int EncodeUnLoginReqInfo(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnLoginReqInfo(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_CLI_GG_Login_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_Login_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_Challenge_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_Challenge_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_Challenge_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_Challenge_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_Login_SUC(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_Login_SUC(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_APLogin_RES(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_APLogin_RES(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_EXPLogin_RES(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_EXPLogin_RES(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_SGILogin_RES(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_SGILogin_RES(void *pHost, CNetData* poNetData);
int EncodeUnPKG_GG_CLI_Login_UN(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnPKG_GG_CLI_Login_UN(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_GG_CLI_Login_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_Login_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_Verify_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_Verify_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_Verify_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_Verify_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_SelectRole_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_SelectRole_REQ(void *pHost, CNetData* poNetData);
int EncodeSelRoleRet(void *pHost, CNetData* poNetData);
int DecodeSelRoleRet(void *pHost, CNetData* poNetData);
int EncodeUnPKG_GG_CLI_SelectRole_UN(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnPKG_GG_CLI_SelectRole_UN(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_GG_CLI_SelectRole_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_SelectRole_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_CreateRole_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_CreateRole_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_CreateRole_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_CreateRole_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_DelRole_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_DelRole_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_DelRole_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_DelRole_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_UnDelRole_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_UnDelRole_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_UnDelRole_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_UnDelRole_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_Logout_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_Logout_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_ReselRole_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_ReselRole_REQ(void *pHost, CNetData* poNetData);
int EncodeUnPKG_GG_CLI_ReselRole_UN(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnPKG_GG_CLI_ReselRole_UN(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_GG_CLI_ReselRole_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_ReselRole_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_KickOff_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_KickOff_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_VerifyStoreEkey_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_VerifyStoreEkey_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_FCMFillInfo_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_FCMFillInfo_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_ReservePwd_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_ReservePwd_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_ReservePwd_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_ReservePwd_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_Extend_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_Extend_MSG(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_Extend_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_Extend_MSG(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_GroupInfo_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_GroupInfo_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_OfflineTrustee_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_OfflineTrustee_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_NeedAuthen_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_NeedAuthen_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_NeedAuthen_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_NeedAuthen_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_QQInfo_NTF(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_QQInfo_NTF(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_InGameVerify_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_InGameVerify_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_InGameVerify_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_InGameVerify_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_FreshVerify_Req(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_FreshVerify_Req(void *pHost, CNetData* poNetData);
int EncodePKG_GG_CLI_LoginVerify_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_GG_CLI_LoginVerify_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_LoginVerify_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_LoginVerify_ACK(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_MERGE_PT_REQ(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_MERGE_PT_REQ(void *pHost, CNetData* poNetData);
int EncodePKG_CLI_GG_MERGE_PT_ACK(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GG_MERGE_PT_ACK(void *pHost, CNetData* poNetData);
/*Encode and Decode Function Declare End*/

typedef int (*EnFuncCCliGgProto)(void *pHost, CNetData* poNetData);
typedef int (*DeFuncCCliGgProto)(void *pHost, CNetData* poNetData);

class CCliGgProto
{
public:
	CCliGgProto();
	~CCliGgProto();
	int Encode(int iMsgID, void *pHost, char *pNet, int iNetSize);
	int Decode(int iMsgID, char *pNet,int iNetSize, void *pHost, int iHostSize);
	int GetPkgSize(int iMsgID) { return m_iPkgSizeArray[iMsgID - CLIGGPROTO_MSGID_OFFSET];}
	EnFuncCCliGgProto FindEncodeFunc(int iMsgID);
	DeFuncCCliGgProto FindDecodeFunc(int iMsgID);
	bool Init();

private:
	EnFuncCCliGgProto m_EncodeFuncArray[CLIGGPROTO_MSGID_RANGE];
	DeFuncCCliGgProto m_DecodeFuncArray[CLIGGPROTO_MSGID_RANGE];
	int m_iPkgSizeArray[CLIGGPROTO_MSGID_RANGE];
	CNetData m_oData;
};

#endif
