/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Zhou Quan                             **
********************************************************************/

/*       Version Number: 1          */

#ifndef CLIGSPROTO_H_INCLUDE_VERSION_1
#define CLIGSPROTO_H_INCLUDE_VERSION_1

#include "NetData.h"
#include "commdefs.h"

/*Defines Begin*/
#define CLIGSPROTO_MSGID_RANGE 2
#define CLIGSPROTO_MSGID_OFFSET 1000
/*Defines End*/


/*Define Structs and Unions        Begin*/
typedef struct tagPKG_CLI_GS_OLD_MSG{
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[CliGsOldMsgLen];
}PKG_CLI_GS_OLD_MSG;

typedef struct tagPKG_GS_CLI_OLD_MSG{
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[CliGsOldMsgLen];
}PKG_GS_CLI_OLD_MSG;

/*Define Structs and Unions        End*/


enum EN_CliGsProto_MessageID
{
	CLI_GS_OLD_MSG                  = 1000        ,
	GS_CLI_OLD_MSG                /*= 1001      */, 
};

/*Encode and Decode Function Declare Begin*/
int EncodePKG_CLI_GS_OLD_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_GS_OLD_MSG(void *pHost, CNetData* poNetData);
int EncodePKG_GS_CLI_OLD_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_GS_CLI_OLD_MSG(void *pHost, CNetData* poNetData);
/*Encode and Decode Function Declare End*/

typedef int (*EnFuncCCliGsProto)(void *pHost, CNetData* poNetData);
typedef int (*DeFuncCCliGsProto)(void *pHost, CNetData* poNetData);

class CCliGsProto
{
public:
	CCliGsProto();
	~CCliGsProto();
	int Encode(int iMsgID, void *pHost, char *pNet, int iNetSize);
	int Decode(int iMsgID, char *pNet,int iNetSize, void *pHost, int iHostSize);
	int GetPkgSize(int iMsgID) { return m_iPkgSizeArray[iMsgID - CLIGSPROTO_MSGID_OFFSET];}
	EnFuncCCliGsProto FindEncodeFunc(int iMsgID);
	DeFuncCCliGsProto FindDecodeFunc(int iMsgID);
	bool Init();

private:
	EnFuncCCliGsProto m_EncodeFuncArray[CLIGSPROTO_MSGID_RANGE];
	DeFuncCCliGsProto m_DecodeFuncArray[CLIGSPROTO_MSGID_RANGE];
	int m_iPkgSizeArray[CLIGSPROTO_MSGID_RANGE];
	CNetData m_oData;
};

#endif
