/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Zhou Quan                             **
********************************************************************/

/*       Version Number: 1          */

#ifndef CLISSPROTO_H_INCLUDE_VERSION_1
#define CLISSPROTO_H_INCLUDE_VERSION_1

#include "netdata.h"
#include "commdefs.h"

/*Defines Begin*/
#define CLISSPROTO_MSGID_RANGE 2
#define CLISSPROTO_MSGID_OFFSET 3000
/*Defines End*/


/*Define Structs and Unions        Begin*/
typedef struct tagPKG_CLI_SS_MSG{
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[CliSsMsgLen];
}PKG_CLI_SS_MSG;

typedef struct tagPKG_SS_CLI_MSG{
	unsigned short   wMsgLen;
	unsigned char    abyMsgData[SsCliMsgLen];
}PKG_SS_CLI_MSG;

/*Define Structs and Unions        End*/


enum EN_CliSsProto_MessageID
{
	CLI_SS_MSG                      = 3000        ,
	SS_CLI_MSG                    /*= 3001      */, 
};

/*Encode and Decode Function Declare Begin*/
int EncodePKG_CLI_SS_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_CLI_SS_MSG(void *pHost, CNetData* poNetData);
int EncodePKG_SS_CLI_MSG(void *pHost, CNetData* poNetData);
int DecodePKG_SS_CLI_MSG(void *pHost, CNetData* poNetData);
/*Encode and Decode Function Declare End*/

typedef int (*EnFuncCCliSsProto)(void *pHost, CNetData* poNetData);
typedef int (*DeFuncCCliSsProto)(void *pHost, CNetData* poNetData);

class CCliSsProto
{
public:
	CCliSsProto();
	~CCliSsProto();
	int Encode(int iMsgID, void *pHost, char *pNet, int iNetSize);
	int Decode(int iMsgID, char *pNet,int iNetSize, void *pHost, int iHostSize);
	int GetPkgSize(int iMsgID) { return m_iPkgSizeArray[iMsgID - CLISSPROTO_MSGID_OFFSET];}
	EnFuncCCliSsProto FindEncodeFunc(int iMsgID);
	DeFuncCCliSsProto FindDecodeFunc(int iMsgID);
	bool Init();

private:
	EnFuncCCliSsProto m_EncodeFuncArray[CLISSPROTO_MSGID_RANGE];
	DeFuncCCliSsProto m_DecodeFuncArray[CLISSPROTO_MSGID_RANGE];
	int m_iPkgSizeArray[CLISSPROTO_MSGID_RANGE];
	CNetData m_oData;
};

#endif
