/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Zhou Quan                             **
********************************************************************/

/*       Version Number: 1          */

#ifndef COMMDEFS_H_INCLUDE_VERSION_1
#define COMMDEFS_H_INCLUDE_VERSION_1

#include "netdata.h"

/*Defines Begin*/
#define SD_CLI_LG_MSG_ID_MIN     1
#define SD_CLI_LG_MSG_ID_MAX     99
#define SD_CLI_GG_MSG_ID_MIN     100
#define SD_CLI_GG_MSG_ID_MAX     999
#define SD_CLI_GS_MSG_ID_MIN     1000
#define SD_CLI_GS_MSG_ID_MAX     2999
#define SD_GG_LG_MSG_ID_MIN      3000
#define SD_GG_LG_MSG_ID_MAX      3099
#define SD_GG_LS_MSG_ID_MIN      3100
#define SD_GG_LS_MSG_ID_MAX      3199
#define SD_GG_DB_MSG_ID_MIN      3200
#define SD_GG_DB_MSG_ID_MAX      3999
#define SD_GG_GS_MSG_ID_MIN      4000
#define SD_GG_GS_MSG_ID_MAX      4999
#define SD_GG_MS_MSG_ID_MIN      5000
#define SD_GG_MS_MSG_ID_MAX      5999
#define SD_GS_DB_MSG_ID_MIN      6000
#define SD_GS_DB_MSG_ID_MAX      7999
#define SD_GS_MS_MSG_ID_MIN      8000
#define SD_GS_MS_MSG_ID_MAX      8999
#define SD_DB_AC_MSG_ID_MIN      9000
#define SD_DB_AC_MSG_ID_MAX      9999
#define PROTO_SUCCESS            1
#define PROTO_FAILURE            0
#define PROTO_AP_RES             2
#define PROTO_EXP_RES            3
#define PROTO_SGI_RES            4
#define HEALTH_TRUE              1
#define HEALTH_FALSE             0
#define LOGIN_PTSDK              0
#define LOGIN_SDOA               1
#define LOGIN_MAIL               2
#define LOGIN_SPETK              5
#define LOGIN_SPEPWD             6
#define LOGIN_AP                 7
#define LOGIN_EXP                8
#define LOGIN_SGI                9
#define LOGOFF_TYPE_LOGOUT       0
#define LOGOFF_TYPE_RESELROLE    1
#define ROLE_MAX_NUM             2
#define ROLENAME_MAX_LEN         15
#define ROLE_MAX_NUM_ALL         20
#define MAX_QUERY_ID_COUNT       16
#define ROLEDATA_LEN             65535
#define PTID_LEN                 21
#define LOGINID_LEN              21
#define MAIL_LEN                 41
#define ACCOUNT_LEN              41
#define PASSWORD_LEN             21
#define DPWD_LEN                 33
#define CHALLENGE_MAX_LEN        27
#define IDCard_MAX_LEN           31
#define NAME_MAX_LEN             33
#define TICKET_MAX_LEN           33
#define SPREADER_LEN             10
#define TOKEN_LEN                1024
#define SPEPWD_LEN               128
#define PHONE_LEN                20
#define AUTHENCODE_LEN           20
#define TEX_MAX_LEN              4096
#define TIME_STRING_LEN          20
#define GROUPNAME_LEN            64
#define REPORT_SIZE              4
#define ONLINEMSG_LEN            4096
#define LOGINMSG_LEN             2048
#define CliGsOldMsgLen           36864
#define CliSsMsgLen              36864
#define SsCliMsgLen              10240000
#define URL_MAX_LEN              2046
#define BENCHMARK_CGS            1
#define BENCHMARK_CS             0
#define BM_DIR_CS                1
#define BM_DIR_SC                0
#define BM_Cli                   0
#define BM_LG                    1
#define BM_LS                    2
#define BM_DB                    3
#define BM_GG                    4
#define BM_MS                    5
#define BM_GS                    6
#define CLIENT_DESKTOP           0
#define CLIENT_FLASH             1
#define CLIENT_GMTOOL            2
#define AP_AUTH_STR_LEN          512
#define AP_AUTH_RES_STR_LEN      512
#define COMMDEFS_MSGID_RANGE 3
#define COMMDEFS_MSGID_OFFSET 9999
/*Defines End*/


/*Define Structs and Unions        Begin*/
typedef struct tagSIPAddr{
	unsigned int     dwIP;
	unsigned short   wPort;
}SIPAddr;

typedef struct tagSErrCode{
	unsigned short   wErrCode;
}SErrCode;

typedef struct tagSRoleBasicInfo{
	char             szRoleName[ROLENAME_MAX_LEN];
	unsigned char    byJob;
	unsigned char    byHair;
	unsigned short   wLevel;
	unsigned char    bySex;
	char             szDeleteTime[TIME_STRING_LEN];
	unsigned char    byDelete;
}SRoleBasicInfo;

typedef struct tagSRoleList{
	unsigned char    bySelect;
	unsigned char    byRoleCount;
	SRoleBasicInfo   astRoleList[ROLE_MAX_NUM_ALL];
}SRoleList;

typedef struct tagSItem{
	unsigned int     dwID;
	unsigned short   wIndex;
	unsigned short   wDura;
	unsigned short   wDuraMax;
	unsigned char    byDemonFlag;
	unsigned short   wEvilAttr1;
	unsigned short   wEvilAttr2;
	unsigned short   wEvilAttr3;
	unsigned char    abyReserved[14];
	unsigned char    abyReserved2[17];
	unsigned char    abyReserved3[16];
}SItem;

typedef struct tagSCreateRoleInfo{
	char             szPTID[PTID_LEN];
	char             szRoleName[ROLENAME_MAX_LEN];
	unsigned char    byHair;
	unsigned char    byJob;
	unsigned char    bySex;
}SCreateRoleInfo;

typedef union tagURoleOpAck{
	SRoleList        stSucc;
	SErrCode         stFail;
}URoleOpAck;

typedef struct tagLoginInfo{
	char             szSpreader[SPREADER_LEN];
	unsigned char    byLockStore;
	unsigned char    byEkeyType;
	unsigned char    byPTType;
	unsigned char    byPWLimited;
	unsigned char    byReferUser;
	unsigned char    byMobileUser;
	unsigned char    bySpreader;
	unsigned char    byANPMove;
	unsigned char    byECardType;
	unsigned char    byECardBindFlag;
	char             szChallenge[CHALLENGE_MAX_LEN];
	char             szProxyTicket[TICKET_MAX_LEN];
}LoginInfo;

typedef struct tagLoginData{
	unsigned char    byFCMFill;
	unsigned short   wMsgLen;
	char             szMsg[LOGINMSG_LEN];
}LoginData;

typedef struct tagPlayerReportInfo{
	char             szGroupName[GROUPNAME_LEN];
	unsigned char    byServerID;
	unsigned int     adwNPlayerNum[REPORT_SIZE];
	unsigned int     adwBPlayerNum[REPORT_SIZE];
}PlayerReportInfo;

typedef struct tagBMTimeVal{
	unsigned int     dwSec;
	unsigned int     dwUSec;
}BMTimeVal;

typedef struct tagCGSNetworkBenchMark{
	unsigned int     dwCliID;
	unsigned int     dwGgID;
	unsigned int     dwSvrID;
	BMTimeVal        stReqCliSendTime;
	BMTimeVal        stReqGgRecvTime;
	BMTimeVal        stReqGgSendTime;
	BMTimeVal        stReqSvrRecvTime;
	BMTimeVal        stAckSvrSendTime;
	BMTimeVal        stAckGgRecvTime;
	BMTimeVal        stAckGgSendTime;
	BMTimeVal        stAckCliRecvTime;
}CGSNetworkBenchMark;

typedef struct tagCSNetworkBenchMark{
	unsigned int     dwCliID;
	unsigned int     dwSvrID;
	BMTimeVal        stReqCliSendTime;
	BMTimeVal        stReqSvrRecvTime;
	BMTimeVal        stAckSvrSendTime;
	BMTimeVal        stAckCliRecvTime;
}CSNetworkBenchMark;

typedef union tagUnBenchMarkBody{
	CGSNetworkBenchMark stCGS;
	CSNetworkBenchMark stCS;
}UnBenchMarkBody;

typedef struct tagPKG_CS_Network_BenchMark_Msg{
	unsigned char    byFrom;
	unsigned char    byTo;
	unsigned char    byDir;
	unsigned char    byType;
	UnBenchMarkBody  stContent;
}PKG_CS_Network_BenchMark_Msg;

typedef struct tagPKG_CS_HeartBeat_Req{
}PKG_CS_HeartBeat_Req;

typedef struct tagPKG_CS_HeartBeat_Ack{
}PKG_CS_HeartBeat_Ack;

/*Define Structs and Unions        End*/


enum EN_CommDefs_MessageID
{
	CS_Network_BenchMark_Msg        = 9999        ,
	CS_HeartBeat_Req              /*= 10000     */, 
	CS_HeartBeat_Ack              /*= 10001     */, 
};

/*Encode and Decode Function Declare Begin*/
int EncodeSIPAddr(void *pHost, CNetData* poNetData);
int DecodeSIPAddr(void *pHost, CNetData* poNetData);
int EncodeSErrCode(void *pHost, CNetData* poNetData);
int DecodeSErrCode(void *pHost, CNetData* poNetData);
int EncodeSRoleBasicInfo(void *pHost, CNetData* poNetData);
int DecodeSRoleBasicInfo(void *pHost, CNetData* poNetData);
int EncodeSRoleList(void *pHost, CNetData* poNetData);
int DecodeSRoleList(void *pHost, CNetData* poNetData);
int EncodeSItem(void *pHost, CNetData* poNetData);
int DecodeSItem(void *pHost, CNetData* poNetData);
int EncodeSCreateRoleInfo(void *pHost, CNetData* poNetData);
int DecodeSCreateRoleInfo(void *pHost, CNetData* poNetData);
int EncodeUnURoleOpAck(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnURoleOpAck(void *pHost, int iSelect, CNetData* poNetData);
int EncodeLoginInfo(void *pHost, CNetData* poNetData);
int DecodeLoginInfo(void *pHost, CNetData* poNetData);
int EncodeLoginData(void *pHost, CNetData* poNetData);
int DecodeLoginData(void *pHost, CNetData* poNetData);
int EncodePlayerReportInfo(void *pHost, CNetData* poNetData);
int DecodePlayerReportInfo(void *pHost, CNetData* poNetData);
int EncodeBMTimeVal(void *pHost, CNetData* poNetData);
int DecodeBMTimeVal(void *pHost, CNetData* poNetData);
int EncodeCGSNetworkBenchMark(void *pHost, CNetData* poNetData);
int DecodeCGSNetworkBenchMark(void *pHost, CNetData* poNetData);
int EncodeCSNetworkBenchMark(void *pHost, CNetData* poNetData);
int DecodeCSNetworkBenchMark(void *pHost, CNetData* poNetData);
int EncodeUnUnBenchMarkBody(void *pHost, int iSelect, CNetData* poNetData);
int DecodeUnUnBenchMarkBody(void *pHost, int iSelect, CNetData* poNetData);
int EncodePKG_CS_Network_BenchMark_Msg(void *pHost, CNetData* poNetData);
int DecodePKG_CS_Network_BenchMark_Msg(void *pHost, CNetData* poNetData);
int EncodePKG_CS_HeartBeat_Req(void *pHost, CNetData* poNetData);
int DecodePKG_CS_HeartBeat_Req(void *pHost, CNetData* poNetData);
int EncodePKG_CS_HeartBeat_Ack(void *pHost, CNetData* poNetData);
int DecodePKG_CS_HeartBeat_Ack(void *pHost, CNetData* poNetData);
/*Encode and Decode Function Declare End*/

typedef int (*EnFuncCCommDefs)(void *pHost, CNetData* poNetData);
typedef int (*DeFuncCCommDefs)(void *pHost, CNetData* poNetData);

class CCommDefs
{
public:
	CCommDefs();
	~CCommDefs();
	int Encode(int iMsgID, void *pHost, char *pNet, int iNetSize);
	int Decode(int iMsgID, char *pNet,int iNetSize, void *pHost, int iHostSize);
	int GetPkgSize(int iMsgID) { return m_iPkgSizeArray[iMsgID - COMMDEFS_MSGID_OFFSET];}
	EnFuncCCommDefs FindEncodeFunc(int iMsgID);
	DeFuncCCommDefs FindDecodeFunc(int iMsgID);
	bool Init();

private:
	EnFuncCCommDefs m_EncodeFuncArray[COMMDEFS_MSGID_RANGE];
	DeFuncCCommDefs m_DecodeFuncArray[COMMDEFS_MSGID_RANGE];
	int m_iPkgSizeArray[COMMDEFS_MSGID_RANGE];
	CNetData m_oData;
};

#endif
