#pragma once
#include <array>

enum string_define
{
	SD_EXECCMDERROR_BADCOMMAND,
	SD_EXECCMDERROR_GMEXECCMDLEVELLOW,
	SD_EXECCMDERROR_PLAYEREXECCMDLEVELLOW,
	SD_CMDRESULTVALUEIS,
	SD_CMDMAPERROR_SCRIPTNOTFOUND,
	SD_CMDMAPERROR_CMDNOTFOUND,
	SD_CMDMAPERROR_CMDALREADYREGISTERED,
	SD_STDERROR_CANNOTPICKUPMOREGOLD,
	SD_STDERROR_YOUHAVEALREADYDEAD,
	SD_ADDTOGUILD_ALREADYOTHERGUILDMEMBER,
	SD_ADDTOGUILD_ALREADYGUILDMEMBER,
	SD_YOUAREBANED,
	SD_ALLOWFRIENDREQUEST,
	SD_REFUSEFRIENDREQUEST,
	SD_YOUALREADYEQUIPAHORSE,
	SD_YOUALREADYHAVEAHORSE,
	SD_MAPNOTALLOWRIDE,
	SD_HORSENOTSETED,
	SD_MAPLIMITED_LOWLEVEL,
	SD_MAPLIMITED_HILEVEL,
	SD_MAPLIMITED_LOWPKPOINT,
	SD_MAPLIMITED_HIPKPOINT,
	SD_MAPLIMITED_WRONGJOB,
	SD_NOFITABLEWEAPONTOUPGRADE,
	SD_ONEWEAPONISUPGRADING,
	SD_WEAPONUPGRADENOENOUGHMATRIAL,
	SD_SPECIALFUNCTIONTURNON,
	SD_UPGRADEWEAPONSUCCESS,
	SD_NOUPGRADEWEAPON,
	SD_NOSPACETOEXPANDBUNDLE,
	SD_THISITEMCANNOTUNBUNDLE,
	SD_MAPLIMITED_NORANDOMMOVE,
	SD_MAPLIMITED_NOESCAPE,
	SD_MAPLIMITED_NOHOME,
	SD_YOURWEAPONGOTEVIL,
	SD_YOURWEAPONGOTFAIL,
	SD_YOURWEAPONGOTLUCKY,
	SD_CANNOTUSESANDCITYHOME,
	SD_STUDYSKILL_WRONGJOB,
	SD_STUDYSKILL_LOWLEVEL,
	SD_TRAINHORSE_NOHORSE,
	SD_CHANGEATTACKMODE,
	SD_PICKUP_BAGFULL,
	SD_PICKUP_WEIGHTFULL,
	SD_PICKUP_NOTYOURS,
	SD_ITEMLIMIT_NODROP,
	SD_ITEMLIMIT_NOTAKEOFF,
	SD_MAX,
};

static const std::array<const char*, SD_MAX> g_xStrings = {
	"您输入了错误的命令",					//	SD_BAGCOMMAND,
	"您的权限不够, 无法执行该GM命令!",		//	SD_GMEXECCMDLEVELLOW
	"您等级不够, 无法使用该命令.",			//	SD_PLAYEREXECCMDLEVELLOW,
	"命令返回值: ",							//	SD_CMDRESULTVALUEIS,
	"命令映射失败, 没有找到页面",			//	SD_CMDMAPERROR_SCRIPTNOTFOUND
	"命令映射失败, 没有找到内部命令",		//	SD_CMDMAPERROR_CMDNOTFOUND
	"命令已经被注册",						//	SD_CMDMAPERROR_CMDALREADYREGISTERED,
	"不能再捡起更多的金钱了",				//	SD_STDERROR_CANNOTPICKUPMOREGOLD
	"您的角色已经死亡, 请重新开始游戏!",	//	SD_STDERROR_YOUHAVEALREADYDEAD
	"对方已经加入行会",						//	SD_GUILDERROR_ALREADYOTHERGUILDMEMBER
	"已经是本行会成员",						//	SD_ADDTOGUILD_ALREADYGUILDMEMBER
	"你被禁言",								//	SD_YOURAREBANED
	"[允许加为好友]",						//	SD_ALLOWFRIENDREQUEST,
	"[拒绝加为好友]",						//	SD_REFUSEFRIENDREQUEST,
	"你已经装备了一个马牌",					//	SD_YOUALREADYEQUIPAHORSE
	"你已经有一匹马了",						//	SD_YOUALREADYHAVEAHORSE
	"本地图不允许骑马",						//	SD_MAPNOTALLOWRIDE
	"该类型的马还没有设置",					//	SD_HORSENOTSETED
	"你的等级太低, 不符合地图要求",			//	SD_MAPLIMITED_LOWLEVEL
	"你的等级太高, 不符合地图要求",			//	SD_MAPLIMITED_HILEVEL
	"你的PK值太低, 不符合地图要求",			//	SD_MAPLIMITED_LOWPKPOINT
	"你的PK值太高, 不符合地图要求",			//	SD_MAPLIMITED_HIPKPOINT
	"你的职业不符合地图要求",				//	SD_MAPLIMITED_WRONGJOB
	"没有合适的武器拿来升级",				//	SD_NOFITABLEWEAPONTOUPGRADE
	"您已经有一把正在升级的武器",			//	SD_ONEWEAPONISUPGRADING
	"没有足够的升级材料",					//	SD_WEAPONUPGRADENOENOUGHMATRIAL
	"特殊功能启动",							//	SD_SPECIALFUNCTIONTURNON
	"升级武器成功",							//	SD_UPGRADEWEAPONSUCCESS
	"没有正在锻造的武器",					//	SD_NOUPGRADEWEAPON
	"没有空间解包",							//	SD_NOSPACETOEXPANDBUNDLE
	"这个物品无法解包",						//	SD_THISITEMCANNOTUNBUNDLE
	"当前地图不能使用随机",					//	SD_MAPLIMITED_NORANDOMMOVE
	"当前地图不能使用逃脱",					//	SD_MAPLIMITED_NOESCAPE
	"当前地图不能使用回城",					//	SD_MAPLIMITED_NOHOME
	"你的武器被诅咒了",						//	SD_YOURWEAPONGOTEVIL
	"你的武器被幸运失败",					//	SD_YOURWEAPONGOTFAIL
	"你的武器获得了幸运",					//	SD_YOURWEAPONGOTLUCKY
	"你不能使用沙城回城",					//	SD_CANNOTUSESANDCITYHOME
	"职业不符, 无法学习此技能",				//	SD_STUDYSKILL_WRONGJOB
	"等级不够, 无法学习此技能",				//	SD_STUDYSKILL_LOWLEVEL
	"你现在还没有马匹",						//	SD_TRAINHORSE_NOHORSE
	"更改模式 CTRL+H",						//	SD_CHANGEATTACKMODE
	"背包满了, 无法捡起",					//	SD_PICKUP_BAGFULL,
	"负重满了, 无法捡起",					//	SD_PICKUP_WEIGHTFULL,
	"物品不属于你, 一定时间范围内不能捡取",	//	SD_PICKUP_NOTYOURS,
	"物品无法被扔掉",						//	SD_ITEMLIMIT_NODROP,
	"物品无法被卸载",						//	SD_ITEMLIMIT_NOTAKEOFF,
};

inline const char* getstrings(string_define sd)
{
	if ((UINT)sd >= (UINT)SD_MAX)return "<nullptr>";
	return g_xStrings[sd];
}
